In [1]:
import numpy as np
import sys

In [2]:
a = [1, 2, 3, 4, 5]
b= np.array([1, 2, 3, 4, 5])

In [3]:
sys.getsizeof(a)

104

In [4]:
sys.getsizeof(b)

152

# Array

### Dimensionamento de Arrays

In [5]:
# Array 1D

d1 = np.array([1,2,3])
print(d1.shape)
print(d1.ndim)

(3,)
1


In [6]:
# Array 2D

d2 = np.array([[1,2,3], [4,5,6]])
print(d2.shape)
print(d2.ndim)

(2, 3)
2


In [7]:
# Array 3D

d3 = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(d3.shape)
print(d3.ndim)

(2, 2, 2)
3


### Soma

In [ ]:
a1 = [2,3,4]
b1 = [2,3,4]

In [ ]:
result = np.add(a1, b1)
print(result)

[4 6 8]


### Selecionando Itens

In [12]:
a = np.array([[1,2,3], [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [13]:
# array[row, collum]
a[0, 2]

np.int64(3)

In [15]:
a[0,:]

array([1, 2, 3])

In [16]:
a[:,1]

array([2, 5])